/**
 * Workaholic Core Domain Constants
 * Authoritative constants matching DOMAIN-MODEL.md and BUSINESS-RULES.md
 */

export const TASK_STATUS = Object.freeze({
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  DONE: 'DONE',
  CANCELLED: 'CANCELLED',
});

export const TASK_PRIORITY = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});

export const DAY_ORDER = Object.freeze({
  DO1: 'DO1',
  DO2: 'DO2',
  DO3: 'DO3',
  DO4: 'DO4',
  DO5: 'DO5',
  DO6: 'DO6',
});

export const CALENDAR_SOURCE = Object.freeze({
  WORKAHOLIC: 'WORKAHOLIC',
  GOOGLE: 'GOOGLE',
  COLLEGE: 'COLLEGE',
  DAY_ORDER: 'DAY_ORDER',
  HOLIDAY: 'HOLIDAY',
  BIRTHDAY: 'BIRTHDAY',
  BOOKING: 'BOOKING',
  IMPORTED: 'IMPORTED',
});

export const WORKSPACE_ROLE = Object.freeze({
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
});

export const ERROR_CODE = Object.freeze({
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
});

export const RECURRENCE_FREQUENCY = Object.freeze({
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
});

export const PLATFORM = Object.freeze({
  WEB: 'WEB',
  WINDOWS: 'WINDOWS',
  ANDROID: 'ANDROID',
});

export const WORKSPACE_TYPE = Object.freeze({
  PERSONAL: 'PERSONAL',
  TEAM: 'TEAM',
});

export const MEMBERSHIP_STATUS = Object.freeze({
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  REMOVED: 'REMOVED',
});

export const DEVICE_TRUST_STATE = Object.freeze({
  TRUSTED: 'TRUSTED',
  UNTRUSTED: 'UNTRUSTED',
  REVOKED: 'REVOKED',
});

export const SESSION_TYPE = Object.freeze({
  WEB: 'WEB',
  DESKTOP: 'DESKTOP',
  MOBILE: 'MOBILE',
  API: 'API',
});

export const JOB_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});
