/**
 * Workaholic Core Domain Constants
 * Authoritative constants matching DOMAIN-MODEL.md and BUSINESS-RULES.md
 */

export const TASK_STATUS = Object.freeze({
  TODO: 'TODO',
  IN_PROGRESS: 'IN_PROGRESS',
  BLOCKED: 'BLOCKED',
  COMPLETED: 'COMPLETED',
  DONE: 'COMPLETED', // Backward-compatible alias resolving to COMPLETED
  CANCELLED: 'CANCELLED',
});

export const TASK_PRIORITY = Object.freeze({
  P0: 'P0', // Critical
  P1: 'P1', // Urgent
  P2: 'P2', // High
  P3: 'P3', // Medium
  P4: 'P4', // Low
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});

export const DEPENDENCY_TYPE = Object.freeze({
  BLOCKS: 'BLOCKS',
  BLOCKED_BY: 'BLOCKED_BY',
  DEPENDS_ON: 'DEPENDS_ON',
  RELATED_TO: 'RELATED_TO',
});

export const TASK_LINK_TYPE = Object.freeze({
  EXTERNAL: 'EXTERNAL',
  INTERNAL: 'INTERNAL',
});

export const WORK_BLOCK_STATUS = Object.freeze({
  SCHEDULED: 'SCHEDULED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
});

export const DAY_ORDER = Object.freeze({
  DO1: 'DO1',
  DO2: 'DO2',
  DO3: 'DO3',
  DO4: 'DO4',
  DO5: 'DO5',
  DO6: 'DO6',
});

export const CALENDAR_SOURCE = Object.freeze({
  WORKAHOLIC: 'WORKAHOLIC',
  GOOGLE: 'GOOGLE',
  COLLEGE: 'COLLEGE',
  DAY_ORDER: 'DAY_ORDER',
  HOLIDAY: 'HOLIDAY',
  BIRTHDAY: 'BIRTHDAY',
  BOOKING: 'BOOKING',
  IMPORTED: 'IMPORTED',
});

export const WORKSPACE_ROLE = Object.freeze({
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
});

export const ERROR_CODE = Object.freeze({
  AUTHENTICATION_REQUIRED: 'AUTHENTICATION_REQUIRED',
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',
  SYNC_CONFLICT: 'SYNC_CONFLICT',
  TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_CONNECTED: 'NOT_CONNECTED',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',
});

export const RECURRENCE_FREQUENCY = Object.freeze({
  DAILY: 'DAILY',
  WEEKLY: 'WEEKLY',
  MONTHLY: 'MONTHLY',
  YEARLY: 'YEARLY',
});

export const RECURRENCE_EDIT_MODE = Object.freeze({
  THIS: 'THIS',
  THIS_AND_FOLLOWING: 'THIS_AND_FOLLOWING',
  SERIES: 'SERIES',
});

export const RECURRENCE_EXCEPTION_TYPE = Object.freeze({
  CANCELLED: 'CANCELLED',
  MODIFIED: 'MODIFIED',
  RESCHEDULED: 'RESCHEDULED',
  COMPLETED: 'COMPLETED',
});

export const WEEKDAY = Object.freeze({
  SU: 0,
  MO: 1,
  TU: 2,
  WE: 3,
  TH: 4,
  FR: 5,
  SA: 6,
});

export const PLATFORM = Object.freeze({
  WEB: 'WEB',
  WINDOWS: 'WINDOWS',
  ANDROID: 'ANDROID',
});

export const WORKSPACE_TYPE = Object.freeze({
  PERSONAL: 'PERSONAL',
  TEAM: 'TEAM',
});

export const MEMBERSHIP_STATUS = Object.freeze({
  INVITED: 'INVITED',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  REMOVED: 'REMOVED',
});

export const DEVICE_TRUST_STATE = Object.freeze({
  TRUSTED: 'TRUSTED',
  UNTRUSTED: 'UNTRUSTED',
  REVOKED: 'REVOKED',
});

export const SESSION_TYPE = Object.freeze({
  WEB: 'WEB',
  DESKTOP: 'DESKTOP',
  MOBILE: 'MOBILE',
  API: 'API',
});

export const JOB_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  DEAD_LETTER: 'DEAD_LETTER',
});

export const JOB_PRIORITY = Object.freeze({
  LOW: 0,
  NORMAL: 5,
  HIGH: 10,
  CRITICAL: 20,
});

export const JOB_TYPE = Object.freeze({
  REMINDER_SWEEP: 'REMINDER_SWEEP',
  REMINDER_DISPATCH: 'REMINDER_DISPATCH',
  NOTIFICATION_DISPATCH: 'NOTIFICATION_DISPATCH',
  CALENDAR_SYNC: 'CALENDAR_SYNC',
  GOOGLE_CALENDAR_SYNC: 'GOOGLE_CALENDAR_SYNC',
  CLEANUP: 'CLEANUP',
});

export const INTEGRATION_PROVIDER = Object.freeze({
  GOOGLE: 'GOOGLE',
});

export const INTEGRATION_STATUS = Object.freeze({
  DISCONNECTED: 'DISCONNECTED',
  AUTHORIZING: 'AUTHORIZING',
  CONNECTED: 'CONNECTED',
  SYNCING: 'SYNCING',
  ERROR: 'ERROR',
  REAUTH_REQUIRED: 'REAUTH_REQUIRED',
});

export const SYNC_STATE = Object.freeze({
  SYNCED: 'SYNCED',
  PENDING_UPLOAD: 'PENDING_UPLOAD',
  PENDING_DOWNLOAD: 'PENDING_DOWNLOAD',
  CONFLICT: 'CONFLICT',
  DELETED_EXTERNALLY: 'DELETED_EXTERNALLY',
  DETACHED: 'DETACHED',
});

export const SYNC_OBJECT_TYPE = Object.freeze({
  CALENDAR: 'CALENDAR',
  EVENT: 'EVENT',
  TASK: 'TASK',
  FILE: 'FILE',
});

export const SYNC_DIRECTION = Object.freeze({
  INCOMING: 'INCOMING',
  OUTGOING: 'OUTGOING',
  BIDIRECTIONAL: 'BIDIRECTIONAL',
});

export const PROJECT_STATUS = Object.freeze({
  ACTIVE: 'ACTIVE',
  ON_HOLD: 'ON_HOLD',
  COMPLETED: 'COMPLETED',
  ARCHIVED: 'ARCHIVED',
  CANCELLED: 'CANCELLED',
});

export const PROJECT_ROLE = Object.freeze({
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
});

export const EVENT_VISIBILITY = Object.freeze({
  PRIVATE: 'PRIVATE',
  SHARED: 'SHARED',
  PUBLIC: 'PUBLIC',
});

export const EVENT_STATUS = Object.freeze({
  CONFIRMED: 'CONFIRMED',
  TENTATIVE: 'TENTATIVE',
  CANCELLED: 'CANCELLED',
});

export const CALENDAR_VISIBILITY = Object.freeze({
  PRIVATE: 'PRIVATE',
  SHARED: 'SHARED',
  PUBLIC: 'PUBLIC',
});

export const CALENDAR_VIEW = Object.freeze({
  DAY: 'DAY',
  WEEK: 'WEEK',
  WORKWEEK: 'WORKWEEK',
  MONTH: 'MONTH',
  AGENDA: 'AGENDA',
});

export const REMINDER_TRIGGER_TYPE = Object.freeze({
  ABSOLUTE_TIME: 'ABSOLUTE_TIME',
  BEFORE_EVENT: 'BEFORE_EVENT',
  BEFORE_DEADLINE: 'BEFORE_DEADLINE',
  RECURRING_TIME: 'RECURRING_TIME',
  EXACT_TIME: 'ABSOLUTE_TIME',
  RELATIVE_EVENT_START: 'BEFORE_EVENT',
  RELATIVE_TASK_DUE: 'BEFORE_DEADLINE',
  RECURRING: 'RECURRING_TIME',
});

export const REMINDER_PRIORITY = Object.freeze({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL',
  MEDIUM: 'NORMAL',
});

export const REMINDER_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  TRIGGERED: 'TRIGGERED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED',
});

export const RECIPIENT_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  DISMISSED: 'DISMISSED',
  SNOOZED: 'SNOOZED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
});

export const NOTIFICATION_TYPE = Object.freeze({
  REMINDER: 'REMINDER',
  TASK_ASSIGNED: 'TASK_ASSIGNED',
  CALENDAR_EVENT: 'CALENDAR_EVENT',
  BOOKING: 'BOOKING',
  COLLABORATION: 'COLLABORATION',
  SYSTEM: 'SYSTEM',
  SHARED_ALERT: 'SHARED_ALERT',
});

export const NOTIFICATION_CHANNEL = Object.freeze({
  IN_APP: 'IN_APP',
  PUSH: 'PUSH',
  WINDOWS_DESKTOP: 'WINDOWS_DESKTOP',
  ANDROID_LOCAL: 'ANDROID_LOCAL',
});

export const DELIVERY_STATUS = Object.freeze({
  PENDING: 'PENDING',
  SENT: 'SENT',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  RETRYING: 'RETRYING',
  CANCELLED: 'CANCELLED',
});

export const TRUSTED_RELATIONSHIP_STATUS = Object.freeze({
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  REVOKED: 'REVOKED',
  BLOCKED: 'BLOCKED',
});

export const TRUSTED_PERMISSION = Object.freeze({
  RECEIVE_REMINDERS: 'trusted.reminders.receive',
  VIEW_CALENDAR: 'trusted.calendar.view',
  VIEW_TASKS: 'trusted.tasks.view',
  EDIT_TASKS: 'trusted.tasks.edit',
});
